visual:
  node_colors:
    M: "blue"
    F: "red"
    U: "black"
  line_styles:
    spouse:
      color: "gray"
      width: 2
      style: "solid"
    sibling:
      color: "black"
      width: 0
      style: "solid"
    parent-child:
      color: "green"
      width: 1
      style: "dashed"
  spacing:
    horizontal: 20
    vertical: 8
  labels:
    wrap: true
    font_size: 8
  title: "Family Tree Visualization"

layout:
  generational_band:
    enabled: true
  nuclear_family_triangle:
    enabled: true
  sibling_adjacency:
    enabled: true
  spouse_adjacency:
    enabled: true
overlap:
  adjustment:
    vertical: true
    max_adjustment: 1
output:
  path: "family_tree.png"
  size:
    width: 24
    height: 16
spacing_weights:
  spouse: 2
  sibling: 20
  parent-child: 30
